const distros = [
  'Arch I3',
  'AbsoluteLinux',
  'AcademiX',
  'AirSlax',
  'alisiOS',
  'AlmaLinux OS',
  'AlpineLinux',
  'ALT Linux',
  'Alter Linux',
  'Amazon Linux',
  'Anarchy Linux',
  'Android-x86',
  'Antergos',
  'Antivirus Live CD',
  'antiX Linux',
  'Apodio',
  'Aptosid',
  'Arabbix',
  'ArchBang',
  'Archcraft',
  'ArchLabs',
  'Archlinux',
  'Archman',
  'ArchStrike',
  'ArcoLinux',
  'ArtixLinux',
  'AryaLinux',
  'Astra Linux',
  'Austrumi',
  'AV LinuxA',
  'AzzeraOS',
  'BackBoxLinux',
  'BEE free',
  'BigLinux',
  'Bio-Linux',
  'BlackArch',
  'BlackBox Linux',
  'BlackLab',
  'BlackPantherOS',
  'BlackSlash',
  'blag',
  'BlankOn',
  'Bliss OS',
  'Bluestar',
  'Bodhi',
  'BOSS Linux',
  'BunsenLabs',
  'ByzantineOS',
  'CAELinux',
  'Caine',
  'Caixa Magica',
  'Calculate Linux Desktop',
  'Canaima',
  'CentOS',
  'Chakra',
  'ChaletOS',
  'ChameleonOS',
  'Chapeau',
  'ClearOS',
  'Clonezilla',
  'CommodoreOS',
  'Condres OS',
  'ConnochaetOS',
  'CROWZ',
  'CRUX',
  'Cucumber',
  'Damn Small Linux',
  'Damn Small Linux Not',
  'Dapper Linux',
  'Daylight Linux',
  'Debian',
  'Debian facile',
  'Debian-FAI',
  'DebianEdu',
  'deepin',
  'DEFT',
  'Devil-Linux',
  'Devuan',
  'Diamond Linux-TT',
  'DragonFly BSD',
  'Dragora',
  'Drauger OS',
  'DuZeru',
  'DVKBuntu',
  'DXT2',
  'Dyne:bolic',
  'EasyOS',
  'Edubuntu',
  'elementaryOS',
  'Elive Linux',
  'Emmabuntüs',
  'Emmi OS',
  'EndeavourOS',
  'Endless OS',
  'EnsoOS',
  'EpiLinux',
  'ERP OS',
  'Escuelas Linux',
  'Estobuntu',
  'Estrellaroja',
  'Exe GNU Linux',
  'ExTiX',
  'Fatdog64',
  'Fedora',
  'Fedora Spins',
  'Fenix OS',
  'FerenOS',
  'Finnix',
  'FLS System',
  'FreeBSD',
  'FreeDOS',
  'FreeNAS',
  'Frenzy',
  'Frugalware',
  'FuguIta',
  'Funtoo',
  'FuryBSD',
  'G4L',
  'Garuda Linux',
  'GeckoLinux',
  'Gentoo',
  'GhostBSD',
  'GNewSense',
  'GNUSTEP',
  'GoboLinux',
  'Gparted',
  'GreenieLinux',
  'GRML',
  'GuixSD',
  'Haiku',
  'hamOS',
  'Hannah Montana Linux',
  'HardenedBSD',
  'HarmoniKR',
  'Heads',
  'HefftorLinux',
  'Huayra',
  'Hyperbola',
  'instantOS',
  'io GNU Linux',
  'Kali GNOME',
  'Kanotix',
  'KaOS',
  'KDE neon',
  'Knoppix',
  'Kodachi',
  'KolibriOS',
  'Korora',
  'Kubuntu',
  'Kubuntu Focus',
  'Kwort',
  'Lernstick',
  'LG3D',
  'LibraZiK',
  'Linkat',
  'Linux Lite',
  'Linux Mint',
  'LinuxConsole',
  'Linuxfx',
  'LiveRaizo',
  'LliureX',
  'LMDE',
  'Lubuntu',
  'LuninuxOS',
  'LXLE OS',
  'MaboxLinux',
  'Macpup',
  'Mageia',
  'MakuluLinux',
  'Manjaro',
  'Matriux',
  'MauiLinux',
  'MenuetOS',
  'MidnightBSD',
  'MikeOS',
  'MilagrOS',
  'MinerOS',
  'Minimal Linux',
  'MiniNo',
  'MINIX',
  'Miraculix',
  'Modicia',
  'Musix',
  'Muslimbuntu',
  'MX Linux',
  'Nanolinux',
  'Nas4Free',
  'NemOs',
  'Neptune',
  'NetBSD',
  'NethServer',
  'Netrunner',
  'Nitrux',
  'NixOs',
  'Nova',
  'NST',
  'NuTyX',
  'obarun',
  'Omni OS',
  'OpenBSD',
  'openEuler',
  'OpenIndiana',
  'openmamba',
  'OpenMandriva',
  'openSUSE',
  'OPNsense',
  'OracleLinux',
  'OS108',
  'OSGeo live',
  'OviOS',
  'Parabola',
  'Pardus',
  'Parrot',
  'Parsix',
  'Parted Magic',
  'PCLinuxOS',
  'PeachOSI',
  'PearOS',
  'Pentoo',
  'PeppermintOS',
  'PinguyOS',
  'Pisi Linux',
  'Plamo Linux',
  'Plasma Mobile',
  'PLD Linux',
  'plopLinux',
  'PNPI-OS',
  'PointLinux',
  'Pop!_OS',
  'PORTEUS',
  'POS OS',
  'PrimTux',
  'PrRescue',
  'PsychOS',
  'Puppy Linux',
  'PureOS',
  'Q4OS',
  'QubesOS',
  'Quirky',
  'Raspberry Pi Desktop',
  'ReactOS',
  'Reborn OS',
  'Red Star OS',
  'Redcore',
  'Redo Rescue',
  'Redox',
  'Refracta',
  'Regata OS',
  'Regolith Linux',
  'releax',
  'Rescatux',
  'Rescuezilla',
  'RevengeOS',
  'RoboLinux',
  'Rockstor',
  'ROSA FRESH',
  'RoshanOS',
  'Runtu',
  'Sabayon',
  'Sabily',
  'Sabotage Linux',
  'SalentOS',
  'Salix',
  'Schulstick Linux',
  'ScientificLinux',
  'SELKS',
  'SemiCode OS',
  'Septor',
  'Siduction',
  'Simplicity Linux',
  'SimplyMEPIS',
  'Slackel',
  'Slackware',
  'Slax',
  'SliTaz',
  'snakeware',
  'Snallinux',
  'Solus',
  'SolydK',
  'SolydX',
  'SparkyLinux',
  'Springdale',
  'STAR',
  'Stresslinux',
  'SubgraphOS',
  'SuperGamer',
  'susOS',
  'SwagArch',
  'SystemRescueCd',
  'Tails',
  'Tanglu',
  'TeArch',
  'Tiny Core',
  'Trident',
  'Trisquel',
  'TROM-Jaro',
  'TrueOS',
  'Tsurugi Linux',
  'TurnKey Linux',
  'Tux N Vape',
  'tuxtrans',
  'Twister OS',
  'Ubuntu XFCE',
  'Ubuntu Budgie',
  'Ubuntu CE',
  'Ubuntu Cinnamon',
  'Ubuntu Mate',
  'Ubuntu Studio',
  'Ubuntu Unity',
  'Ubuntu Unity Remix',
  'Ubuntu Web',
  'UbuntuDDE',
  'UbuntuKylin',
  'Ubuntuvn',
  'Ufficio Zero',
  'Ultimate Edition',
  'UmVirt Linux From Scratch',
  'Uruk',
  'VectorLinux',
  'Venom Linux',
  'VineLinux',
  'VoidLinux',
  'Volumio',
  'Voyager',
  'VyOS',
  'WattOs',
  'Wifislax',
  'Window Maker Live',
  'Windowsfx',
  'Xevuan',
  'Xubuntu',
  'Zentyal',
  'Zenwalk',
  'Zeroshell',
  'Zevenet',
  'Zorin OS',
];

const distroMap = {};

const list = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'.split('');

list.forEach((item) => {
  distroMap[item] = distros.filter((distro) => distro.startsWith(item));
});

export default distroMap;
